import type { SpeedDisplayUnit } from '../../../../utils/speedUnits';
import { speedUnitTooltipWord } from '../../../../utils/speedUnits';

/** Per-mode table config: column order, header names, and tooltips. Keys match API column names (case-insensitive match used). */
export type ViewTableConfig = { columnOrder: string[]; columns: Record<string, { header: string; tooltip: string }> };

export function buildPrestartTableConfig(unit: SpeedDisplayUnit): Record<string, ViewTableConfig> {
  const s = speedUnitTooltipWord(unit);
  return {
    prestart: {
      columnOrder: [
        'RANK',
        'TEAM',
        'Prestart_dist',
        'Bsp_start',
        'Twa_start',
        'DTL_start',
        'LINE_PERC_start',
        'RATIO_turnback',
        'TTK_turnback',
        'TTK_burn',
        'Bsp_avg_pre',
        'Time_turnback',
        'DTL_turnback',
      ],
      columns: {
        RANK: { header: 'Rank', tooltip: 'Position ranked by distance sailed to mark 1 in first 10 seconds' },
        TEAM: { header: 'Team', tooltip: 'Boat / source name' },
        Prestart_dist: {
          header: 'Distance [M]',
          tooltip: 'Distance sailed toward mark 1 in first 10 seconds of race after crossing start line.',
        },
        Bsp_start: { header: 'BSP start', tooltip: `Boat speed (${s}) at start` },
        Twa_start: { header: 'TWA start', tooltip: 'True wind angle (deg) at start' },
        DTL_start: { header: 'DTL start', tooltip: 'Distance to line (m) at start' },
        LINE_PERC_start: { header: 'Line % start', tooltip: 'Line percentage at start' },
        RATIO_turnback: { header: 'Ratio turnback', tooltip: 'Start ratio at turnback' },
        TTK_turnback: { header: 'TTK turnback', tooltip: 'Time to kill (s) at turnback' },
        TTK_burn: { header: 'TTK burn', tooltip: 'Time to kill (s) at burn / BSP min' },
        Bsp_avg_pre: { header: 'BSP avg pre', tooltip: `Average boat speed (${s}) before turnback` },
        Time_turnback: { header: 'Time turnback', tooltip: 'Time (s) at turnback' },
        DTL_turnback: { header: 'DTL turnback', tooltip: 'Distance to line (m) at turnback' },
      },
    },
    acceleration: {
      columnOrder: [
        'RANK',
        'TEAM',
        'Time_accmax',
        'Accel_max',
        'Bsp_accmax',
        'Twa_accmax',
        'Heel_accmax',
        'RH_lwd_accmax',
        'Cant_accmax',
        'Jib_sheet_load_accmax',
        'Jib_cunno_load_accmax',
        'Jib_lead_ang_accmax',
        'Wing_clew_pos_accmax',
        'Wing_twist_accmax',
        'CA1_accmax',
      ],
      columns: {
        RANK: { header: 'Rank', tooltip: 'Position ranked by max acceleration' },
        TEAM: { header: 'Team', tooltip: 'Boat / source name' },
        Time_accmax: { header: 'Time at acc max', tooltip: 'Time (s) when acceleration was maximum' },
        Accel_max: { header: 'Accel max', tooltip: 'Maximum acceleration (m/s²)' },
        Bsp_accmax: { header: 'BSP at acc max', tooltip: `Boat speed (${s}) at max acceleration` },
        Twa_accmax: { header: 'TWA at acc max', tooltip: 'True wind angle (deg) at max acceleration' },
        Heel_accmax: { header: 'Heel at acc max', tooltip: 'Heel angle (deg) at max acceleration' },
        RH_lwd_accmax: { header: 'RH lwd at acc max', tooltip: 'Rudder height (mm) at max acceleration' },
        Cant_accmax: { header: 'Cant at acc max', tooltip: 'Cant angle (deg) at max acceleration' },
        Jib_sheet_load_accmax: { header: 'Jib sheet at acc max', tooltip: 'Jib sheet load (kgf) at max acceleration' },
        Jib_cunno_load_accmax: { header: 'Jib cunno at acc max', tooltip: 'Jib cunningham load (kgf) at max acceleration' },
        Jib_lead_ang_accmax: { header: 'Jib lead ang at acc max', tooltip: 'Jib lead angle (deg) at max acceleration' },
        Wing_clew_pos_accmax: { header: 'Wing clew at acc max', tooltip: 'Wing clew position (mm) at max acceleration' },
        Wing_twist_accmax: { header: 'Wing twist at acc max', tooltip: 'Wing twist (deg) at max acceleration' },
        CA1_accmax: { header: 'CA1 at acc max', tooltip: 'CA1 angle (deg) at max acceleration' },
      },
    },
    maxbsp: {
      columnOrder: [
        'RANK',
        'TEAM',
        'Time_bspmax',
        'Bsp_max',
        'Twa_bspmax',
        'Heel_bspmax',
        'RH_lwd_bspmax',
        'Cant_bspmax',
        'Jib_sheet_load_bspmax',
        'Jib_cunno_load_bspmax',
        'Jib_lead_ang_bspmax',
        'Wing_clew_pos_bspmax',
        'Wing_twist_bspmax',
        'CA1_bspmax',
      ],
      columns: {
        RANK: { header: 'Rank', tooltip: 'Position ranked by max boat speed' },
        TEAM: { header: 'Team', tooltip: 'Boat / source name' },
        Time_bspmax: { header: 'Time at BSP max', tooltip: 'Time (s) when boat speed was maximum' },
        Bsp_max: { header: 'BSP max', tooltip: `Maximum boat speed (${s})` },
        Twa_bspmax: { header: 'TWA at BSP max', tooltip: 'True wind angle (deg) at max boat speed' },
        Heel_bspmax: { header: 'Heel at BSP max', tooltip: 'Heel angle (deg) at max boat speed' },
        RH_lwd_bspmax: { header: 'RH lwd at BSP max', tooltip: 'Rudder height (mm) at max boat speed' },
        Cant_bspmax: { header: 'Cant at BSP max', tooltip: 'Cant angle (deg) at max boat speed' },
        Jib_sheet_load_bspmax: { header: 'Jib sheet at BSP max', tooltip: 'Jib sheet load (kgf) at max boat speed' },
        Jib_cunno_load_bspmax: { header: 'Jib cunno at BSP max', tooltip: 'Jib cunningham load (kgf) at max boat speed' },
        Jib_lead_ang_bspmax: { header: 'Jib lead ang at BSP max', tooltip: 'Jib lead angle (deg) at max boat speed' },
        Wing_clew_pos_bspmax: { header: 'Wing clew at BSP max', tooltip: 'Wing clew position (mm) at max boat speed' },
        Wing_twist_bspmax: { header: 'Wing twist at BSP max', tooltip: 'Wing twist (deg) at max boat speed' },
        CA1_bspmax: { header: 'CA1 at BSP max', tooltip: 'CA1 angle (deg) at max boat speed' },
      },
    },
    reach: {
      columnOrder: [
        'RANK',
        'TEAM',
        'Reach_dist',
        'Bsp_avg_reach',
        'TTK_turnback',
        'RATIO_turnback',
        'DTL_start',
        'LINE_PERC_start',
        'Bsp_start',
        'Twa_start',
        'Accel_max',
        'Bsp_max',
      ],
      columns: {
        RANK: { header: 'Rank', tooltip: 'Position ranked by reach distance (max distance = 1)' },
        TEAM: { header: 'Team', tooltip: 'Boat / source name' },
        Reach_dist: { header: 'Reach dist [m]', tooltip: 'Distance (m) sailed to reach the mark' },
        Bsp_avg_reach: { header: 'BSP avg reach', tooltip: `Average boat speed (${s}) over the reach leg` },
        TTK_turnback: { header: 'TTK turnback', tooltip: 'Time to kill (s) at turnback' },
        RATIO_turnback: { header: 'Ratio turnback', tooltip: 'Start ratio at turnback' },
        DTL_start: { header: 'DTL start', tooltip: 'Distance to line (m) at start' },
        LINE_PERC_start: { header: 'Line % start', tooltip: 'Line percentage at start' },
        Bsp_start: { header: 'BSP start', tooltip: `Boat speed (${s}) at start` },
        Twa_start: { header: 'TWA start', tooltip: 'True wind angle (deg) at start' },
        Accel_max: { header: 'Accel max', tooltip: 'Maximum acceleration (m/s²)' },
        Bsp_max: { header: 'BSP max', tooltip: `Maximum boat speed (${s})` },
      },
    },
    leg1: {
      columnOrder: [
        'RANK',
        'TEAM',
        'Leg1_dist',
        'TTK_turnback',
        'RATIO_turnback',
        'DTL_start',
        'LINE_PERC_start',
        'Bsp_start',
        'Twa_start',
        'Accel_max',
        'Bsp_max',
      ],
      columns: {
        RANK: { header: 'Rank', tooltip: 'Position by leg1 distance (max distance = 1)' },
        TEAM: { header: 'Team', tooltip: 'Boat / source name' },
        Leg1_dist: { header: 'Leg1 dist [m]', tooltip: 'Distance (m) sailed on leg 1 (ranking metric)' },
        TTK_turnback: { header: 'TTK turnback', tooltip: 'Time to kill (s) at turnback' },
        RATIO_turnback: { header: 'Ratio turnback', tooltip: 'Start ratio at turnback' },
        DTL_start: { header: 'DTL start', tooltip: 'Distance to line (m) at start' },
        LINE_PERC_start: { header: 'Line % start', tooltip: 'Line percentage at start' },
        Bsp_start: { header: 'BSP start', tooltip: `Boat speed (${s}) at start` },
        Twa_start: { header: 'TWA start', tooltip: 'True wind angle (deg) at start' },
        Accel_max: { header: 'Accel max', tooltip: 'Maximum acceleration (m/s²)' },
        Bsp_max: { header: 'BSP max', tooltip: `Maximum boat speed (${s})` },
      },
    },
  };
}
