/**
 * Compare racesight_backup_empty.sql (dev) with production_backup_empty.sql (production)
 * and output SQL statements to migrate production to match dev
 * 
 * Usage: node scripts/compare_schemas.js
 */

const fs = require('fs');
const path = require('path');

const projectRoot = path.join(__dirname, '..');
const devSchemaPath = path.join(projectRoot, 'database', 'racesight_backup_empty.sql');
const prodSchemaPath = path.join(projectRoot, 'database', 'production_backup_empty.sql');

console.log('Comparing schemas...');
console.log(`Dev schema: ${devSchemaPath}`);
console.log(`Prod schema: ${prodSchemaPath}`);
console.log('');

// Try to read both files
let devContent, prodContent;

try {
  // Try reading as UTF-8 first
  devContent = fs.readFileSync(devSchemaPath, 'utf8');
} catch (error) {
  try {
    // Try reading as UTF-16LE (Windows encoding)
    devContent = fs.readFileSync(devSchemaPath, 'utf16le');
  } catch (error2) {
    console.error('Error reading dev schema file:', error2.message);
    console.error('File may be binary or have unsupported encoding.');
    process.exit(1);
  }
}

try {
  prodContent = fs.readFileSync(prodSchemaPath, 'utf8');
} catch (error) {
  console.error('Error reading production schema file:', error.message);
  process.exit(1);
}

// Extract CREATE TABLE statements
function extractTables(content, schemaName) {
  const tables = new Map();
  const tableRegex = /CREATE TABLE\s+([\w.]+)\s*\(([\s\S]*?)\);/gi;
  let match;
  
  while ((match = tableRegex.exec(content)) !== null) {
    const fullTableName = match[1];
    const tableDef = match[2];
    tables.set(fullTableName, {
      name: fullTableName,
      definition: tableDef.trim(),
      fullMatch: match[0]
    });
  }
  
  return tables;
}

// Extract CREATE SEQUENCE statements
function extractSequences(content) {
  const sequences = new Map();
  const seqRegex = /CREATE SEQUENCE\s+([\w.]+)\s*([\s\S]*?);/gi;
  let match;
  
  while ((match = seqRegex.exec(content)) !== null) {
    const fullSeqName = match[1];
    const seqDef = match[2];
    sequences.set(fullSeqName, {
      name: fullSeqName,
      definition: seqDef.trim(),
      fullMatch: match[0]
    });
  }
  
  return sequences;
}

// Extract CREATE INDEX statements
function extractIndexes(content) {
  const indexes = new Map();
  const idxRegex = /CREATE\s+(?:UNIQUE\s+)?INDEX\s+(?:IF NOT EXISTS\s+)?([\w.]+)\s+ON\s+([\w.]+)\s*\(([^)]+)\)/gi;
  let match;
  
  while ((match = idxRegex.exec(content)) !== null) {
    const idxName = match[1];
    const tableName = match[2];
    const columns = match[3];
    indexes.set(idxName, {
      name: idxName,
      table: tableName,
      columns: columns,
      fullMatch: match[0]
    });
  }
  
  return indexes;
}

// Extract ALTER TABLE statements (for constraints, etc.)
function extractAlterTables(content) {
  const alters = [];
  const alterRegex = /ALTER TABLE\s+([\w.]+)\s+([\s\S]*?);/gi;
  let match;
  
  while ((match = alterRegex.exec(content)) !== null) {
    alters.push({
      table: match[1],
      statement: match[0]
    });
  }
  
  return alters;
}

console.log('Extracting schema objects...');
const devTables = extractTables(devContent, 'dev');
const prodTables = extractTables(prodContent, 'prod');
const devSequences = extractSequences(devContent);
const prodSequences = extractSequences(prodContent);
const devIndexes = extractIndexes(devContent);
const prodIndexes = extractIndexes(prodContent);

console.log(`Dev: ${devTables.size} tables, ${devSequences.size} sequences, ${devIndexes.size} indexes`);
console.log(`Prod: ${prodTables.size} tables, ${prodSequences.size} sequences, ${prodIndexes.size} indexes`);
console.log('');

// Generate migration SQL
const migrationSQL = [];

migrationSQL.push('-- Migration SQL to update production database to match racesight (dev) schema');
migrationSQL.push('-- Generated by compare_schemas.js');
migrationSQL.push('-- WARNING: Review this SQL carefully before executing on production!');
migrationSQL.push('');
migrationSQL.push('BEGIN;');
migrationSQL.push('');

// Find tables that exist in dev but not in prod
console.log('Checking for new tables in dev...');
for (const [tableName, tableDef] of devTables) {
  if (!prodTables.has(tableName)) {
    console.log(`  NEW TABLE: ${tableName}`);
    migrationSQL.push(`-- Create new table: ${tableName}`);
    migrationSQL.push(tableDef.fullMatch);
    migrationSQL.push('');
  }
}

// Find sequences that exist in dev but not in prod
console.log('Checking for new sequences in dev...');
for (const [seqName, seqDef] of devSequences) {
  if (!prodSequences.has(seqName)) {
    console.log(`  NEW SEQUENCE: ${seqName}`);
    migrationSQL.push(`-- Create new sequence: ${seqName}`);
    migrationSQL.push(seqDef.fullMatch);
    migrationSQL.push('');
  }
}

// Find indexes that exist in dev but not in prod
console.log('Checking for new indexes in dev...');
for (const [idxName, idxDef] of devIndexes) {
  if (!prodIndexes.has(idxName)) {
    console.log(`  NEW INDEX: ${idxName} on ${idxDef.table}`);
    migrationSQL.push(`-- Create new index: ${idxName}`);
    migrationSQL.push(`CREATE INDEX IF NOT EXISTS ${idxName} ON ${idxDef.table}(${idxDef.columns});`);
    migrationSQL.push('');
  }
}

migrationSQL.push('COMMIT;');
migrationSQL.push('');
migrationSQL.push('-- Migration complete. Review the changes above before executing.');

// Output the migration SQL
const outputPath = path.join(projectRoot, 'database', 'migrations', 'migrate_to_racesight.sql');
fs.writeFileSync(outputPath, migrationSQL.join('\n'), 'utf8');

console.log('');
console.log(`Migration SQL written to: ${outputPath}`);
console.log('');
console.log('Summary:');
console.log(`  New tables: ${Array.from(devTables.keys()).filter(t => !prodTables.has(t)).length}`);
console.log(`  New sequences: ${Array.from(devSequences.keys()).filter(s => !prodSequences.has(s)).length}`);
console.log(`  New indexes: ${Array.from(devIndexes.keys()).filter(i => !prodIndexes.has(i)).length}`);
console.log('');
console.log('NOTE: This script only detects NEW objects. For column changes, constraints, etc.,');
console.log('you may need to manually compare the schema files or use a tool like pgdiff/migra.');
